const { test, expect } = require('@playwright/test');
const POManager = require('../pageobjects/POManager');

let usernameGlobal = "santiago@gmail.com";
let passwordGlobal = "aB#45678";
let productNameGlobal = 'IPHONE 13 PRO';
let creditCardNumberGlobal = '4543993192922294';
let firstNameGlobal = "Santiago";
let lastNameGlobal = "Castanon";
let phoneGlobal = "4426244709";
let occupationGlobal = "Engineer";
let genderGlobal = "Male";
let nameOnCardGlobal = "santiago castanon";
let cvv = "333";
let monthExpiry = "11";
let yearExpiry = "28";
const country = "Mexico";

test.only('Create order', async ({page})=>{
    const poManager = new POManager(page);
    const loginPage = poManager.getLoginPage();
    await loginPage.goTo();
    await loginPage.login(usernameGlobal, passwordGlobal);
    const homePage = poManager.getHomePage();
    await homePage.addProductToCart(productNameGlobal);
    await homePage.navigateToCart();
    const cartPage = poManager.getCartPage();
    const isProductNameVisible = await cartPage.isTextVisibleCart(productNameGlobal);
    await expect(isProductNameVisible).toBeTruthy();
    await cartPage.navigateToCheckout();
    const checkoutPage = poManager.getCheckoutPage();
    const productInfo = await checkoutPage.isProductInfoMatching();
    await expect(productInfo[0].trim()).toBe(productNameGlobal.trim());
    await expect(productInfo[1].trim()).toBe("Quantity: 1".trim());
    await checkoutPage.fillCreditCardInfo(creditCardNumberGlobal, monthExpiry, yearExpiry,cvv,nameOnCardGlobal);
    await checkoutPage.addCoupon("rahulshettyacademy");
    await expect(checkoutPage.loadSpinner).not.toBeAttached();
    const isCouponVisible = await checkoutPage.isCouponVisible();
    await expect(isCouponVisible).toBeTruthy();
    await checkoutPage.fillShippingInfo(country);
    await expect(checkoutPage.emailBox).toHaveValue(usernameGlobal);
    await checkoutPage.navigateToConfirmation();
    const orderConfirmationPage = poManager.getOrderConfirmationPage();
    await expect(orderConfirmationPage.thankyoumsg).toBeVisible();
    const orderId = await orderConfirmationPage.getOrdersId();
    await orderConfirmationPage.navigateToOrderHistory();
    const orderhistoryPage = poManager.getOrderHistoryPage();
    expect(await orderhistoryPage.isOrderIDDisplayed(orderId)).toBeTruthy();
    orderhistoryPage.navigateToOrderSummaryPage(orderId);
    const orderSummaryPage = poManager.getOrderSummaryPage();
    await expect(orderSummaryPage.orderSummayTxt).toHaveText("order summary");
    await expect(orderSummaryPage.orderId).toHaveText(orderId);
    await expect(orderSummaryPage.billingCountry).toContainText(country);
    await expect(orderSummaryPage.deliveryCountry).toContainText(country);
    await expect(orderSummaryPage.deliveryEmail).toHaveText(usernameGlobal);
    await expect(orderSummaryPage.billingEmail).toHaveText(usernameGlobal);
    await expect(orderSummaryPage.productName).toHaveText(productNameGlobal);
});

test('Create account', async ({page})=>{
    const poManager = new POManager(page);
    const loginPage = poManager.getRegisterPage();
    await loginPage.goTo();
    await loginPage.registerLink.click();
    const registerPage = new RegisterPage(page);
    await registerPage.register(firstNameGlobal, lastNameGlobal, usernameGlobal, phoneGlobal, passwordGlobal, occupationGlobal, genderGlobal);
});
